djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
                # path(r'', views.index, name='index'),
                # path(r'about/', views.about, name='about'),
                # path('detail/<str:cat_no>/', views.detail, name='detail_view'),
                # path(r'lab6a/', views.new_index, name='new_index'),
                # path(r'lab6a/about', views.new_about, name='new_about'),
                # path('lab6a/detail/<str:cat_no>/', views.new_detail, name='new_detail'),
                path(r'', views.part2_index, name='part2_index'),
                path(r'about/', views.part2_about, name='part2_about'),
                path('detail/<str:cat_no>/', views.part2_detail, name='part2_detail'),
                path('products/', views.products, name='products'),
                path('place_order/', views.place_order, name='place_order'),
                path('products/<str:prod_id>', views.productdetail, name='productdetail'),
                path(r'login/', views.user_login, name='login'),
                path(r'register/', views.user_register, name='register'),
                path(r'logout/', views.user_logout, name='logout'),
                path(r'reset_password/', views.reset_password, name='reset_password'),
                path(r'myorders/', views.myorders, name='myorders'),
                path(r'myprofile/', views.myprofile, name='myprofile')
]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils import timezone
from django.db import models
from django.utils.timezone import now
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    # indicates the city where warehouses for this category of products is located
    # Add a new required field warehouse 
    warehouse = models.CharField(blank=False, default='', max_length=200)

    def __str__(self):
        return 'Category: ' + self.name + ' Warehouse: ' + self.warehouse


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)

    name = models.CharField(max_length=200)

    price = models.DecimalField(max_digits=10, decimal_places=2)

    stock = models.PositiveIntegerField(default=100, validators=[
        MaxValueValidator(1000),
        MinValueValidator(0)
    ])

    available = models.BooleanField(default=True)

    # This field indicates how many people are interested in this product. The default value for the field is 0.
    interested = models.PositiveIntegerField(default=0)

    # blank=True makes field optional
    description = models.TextField(blank=True)

    # This method is used to replenishments for a particular product. When refill(self) is called, it adds 50 to
    # the current value of the stock field for the specified product
    # Method for Feature3
    def refill(self):
        self.stock += 50
        self.available = True
        self.save()

    def __str__(self):
        return 'Product: ' + self.name + ' Price: ' + str(self.price) + ' Stock: ' + str(
            self.stock) + ' Available: ' + str(self.available) + ' Category: ' + self.category.name


class Client(User):
    PROVINCE_CHOICES = [
        (
            'AB', 'Alberta'
        ),
        (
            'MB', 'Manitoba'
        ),
        (
            'ON', 'Ontario'
        ),
        (
            'QC', 'Quebec'
        ), ]

    company = models.CharField(max_length=50, blank=True)

    shipping_address = models.CharField(max_length=300, null=True, blank=True)

    city = models.CharField(max_length=20, default='Windsor')

    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')

    interested_in = models.ManyToManyField(Category, blank=True)

    image = models.ImageField(null=True, blank=True, upload_to='images/')

    # method for Feature2
    def interests(self):
        return ", ".join([category.name for category in self.interested_in.all()])

    def __str__(self):
        return 'Client: ' + self.first_name + ' ' + self.last_name + ' City: ' + self.city + ' Province: ' + self.province


class Center(models.Model):
    # Update the name field of Center model to be unique.
    name = models.CharField(max_length=50, unique=True)
    address = models.CharField(max_length=100)


class Course(models.Model):
    type = models.CharField(max_length=50)
    # Make the field number the primary key for the model Course
    number = models.IntegerField(primary_key=True)
    price = models.IntegerField()
    min_age = models.IntegerField()
    # Update the Course model to indicate that description field is optional.
    description = models.CharField(max_length=200, blank=True)
    available = models.BooleanField()
    # create a new field Center in Course model that refers to an instance of Center model with
    # “many-to-one” relationship. So, a center can provide many courses and each course is provided by
    # exactly one center.
    center = models.ForeignKey(Center, related_name='center_course', on_delete=models.CASCADE)

    def __str__(self):
        return 'Type:' + self.type + 'Center Name: ' + self.center.name


class Order(models.Model):
    # indicates the product that was ordered
    product = models.ForeignKey(Product, related_name='order_product', on_delete=models.CASCADE)

    # indicates the client that ordered the product
    client = models.ForeignKey(Client, related_name='order_client', on_delete=models.CASCADE)

    # indicates how many items were ordered
    num_units = models.PositiveIntegerField()

    ORDER_STATUS_CHOICES = [
        (
            0, 'Order Cancelled'
        ),
        (
            1, 'Order Placed'
        ),
        (
            2, 'Order Shipped'
        ),
        (
            3, 'Order Delivered'
        ), ]

    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=1)

    # indicates the date the order_status was last updated
    status_date = models.DateTimeField(default=now)

    # For the Order model, write a method total_cost(self) that returns the total cost for all items in the order.
    def total_cost(self):
        return self.product.price * self.num_units

    def __str__(self):
        return 'Order: ' + self.product.name + ' Client: ' + self.client.username + ' Num_units: ' + str(self.num_units)


class PasswordReset(models.Model):
    username = models.CharField(max_length=200)

    def __str__(self):
        return self.username

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, reverse
from django.http import HttpResponse
from .models import Category, Product, Client, Order
from .forms import OrderForm, InterestForm, ClientForm, PasswordResetForm
# lab8-Import necessary classes and models
from django.contrib.auth import authenticate, login, logout, hashers
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail
from datetime import datetime
import random
import string


# Create your views here.
def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    response = HttpResponse()
    heading1 = '<p>' + 'List of categories: ' + '</p>'
    response.write(heading1)
    for category in cat_list:
        para = '<p>' + str(category.id) + ': ' + str(category) + '</p>'
        response.write(para)

    # Update the index view function, so it displays a list of up to 5 Products as well. The Products should
    # be sorted in descending order of price (i.e. most expensive first).
    prod_list = Product.objects.all().order_by('-price')[:5]
    heading2 = '<p>' + 'List of products: ' + '</p>'
    response.write(heading2)
    for product in prod_list:
        para = '<p>' + str(product.id) + ': ' + str(product) + '</p>'
        response.write(para)

    return response


# Task2
def about(request):
    response = HttpResponse()
    heading = '<p>' + 'This is an Online Store APP.' + '<p>'
    response.write(heading)

    return response


# Task3
def detail(request, cat_no):
    response = HttpResponse()
    category = get_object_or_404(Category, pk=cat_no)
    locationHeading = '<p>' + 'Warehouse Location: ' + category.warehouse + '<p>'
    response.write(locationHeading)
    products = Product.objects.filter(category=category)
    heading2 = '<p>' + 'List of products: ' + '</p>'
    response.write(heading2)
    for product in products:
        para = '<p>' + str(product.id) + ': ' + str(product) + '</p>'
        response.write(para)

    return response


# Lab 6 starts from here using new functions for it rather than updating the previous ones.

# 1. Created directory for all the templates
# 2. Created new_index in the views.py

# 3. Created new index0.html and connected it with the new_index function in views.py solved all the subquestion in
# this part for question 5 Updated the index function such that clikcing on the category will foward you to page of
# each category ith its products
def new_index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index0.html', {'cat_list': cat_list})


# 4. Created new about0.html and connected it with new_about functiuon in views.py
# solved all the sub question in this part
def new_about(request):
    # Yes. created a new context variable
    heading = 'This is an online store app of U windsor'
    # passing the varibale created in the about part to the render function
    return render(request, 'myapp/about0.html', {'x': heading})


# 5. Created new detail0.html and connected it with new_detail function in views.py
# solved all the subquestion in this part
def new_detail(request, cat_no):
    category = get_object_or_404(Category, pk=cat_no)
    products = Product.objects.filter(category=category)
    return render(request, 'myapp/detail0.html', {'category': category, 'products': products})


# Lab 6 part2 starts from here and all the changes are stored in the new html files to understand the template inheritance.

# Used style.css from static folder and created new base.html for each of the below functions to help us learn the over ride in template inheritance

def part2_index(request):
    # cat_list = Category.objects.all().order_by('id')[:10]
    cat_list = Category.objects.all()
    if 'last_login' in request.session:
        last_login = request.session['last_login']
    else:
        last_login = 'Your last login was more than one hour ago'
    return render(request, 'myapp/index.html', {'cat_list': cat_list, 'last_login': last_login})


def part2_about(request):
    heading = 'This is an online store app of U windsor'
    if 'about_visits' in request.session:
        request.session['about_visits'] += 1
    else:
        request.session['about_visits'] = 1
        request.session.set_expiry(300)
    return render(request, 'myapp/about.html', {'x': heading, 'about_visits': request.session['about_visits']})


def part2_detail(request, cat_no):
    category = get_object_or_404(Category, pk=cat_no)
    products = Product.objects.filter(category=category)
    return render(request, 'myapp/detail.html', {'category': category, 'products': products})


# Lab 7 -->
def products(request):
    # prodlist = Product.objects.all().order_by('id')[:10]
    prodlist = Product.objects.all()
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.save()
                # the function updates the stock field of the corresponding product
                order.product.stock -= order.num_units
                if order.product.stock == 0:
                    order.product.available = False
                order.product.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
        return render(request, 'myapp/place_order.html', {'form': form, 'msg': msg, 'prodlist': prodlist})


def productdetail(request, prod_id):
    product = get_object_or_404(Product, pk=prod_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form.cleaned_data["interested"] == "1":
                product.interested = product.interested + 1
                product.save()
                return redirect('/myapp/')
            else:
                return redirect('/myapp/')
        else:
            msg = 'There was an error in saving. Please try again'
            return render(request, 'myapp/interest_response.html', {'msg': msg})
    else:
        form = InterestForm()
        return render(request, 'myapp/productdetail.html', {'form': form, 'product': product})


# Lab 8
# generate the date and time of the current login. Store this value as a session 
def user_login(request):
    if request.user.is_authenticated:
        return redirect('myapp:part2_index')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = datetime.now().strftime("%B %d, %Y- %H:%M:%S")
                request.session.set_expiry(3600)
                if request.POST.get('next') != '':
                    return redirect(request.POST.get('next'))
                else:
                    return HttpResponseRedirect(reverse('myapp:part2_index'))
            else:
                # return HttpResponse('Your account is disabled.')
                return render(request, 'myapp/generic_response.html', {'response': 'Your account is disabled.'})
        else:
            # return HttpResponse('Invalid login details.')
            return render(request, 'myapp/generic_response.html', {'response': 'Invalid login details.'})
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:part2_index'))


# Feature4
def user_register(request):
    if request.user.is_authenticated:
        return redirect('myapp:part2_index')

    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES or None)
        if form.is_valid():
            client = form.save(commit=False)
            client.set_password(client.password)
            client.save()
            form.save_m2m()

            msg = 'Congratulations, You are now registered as a Client'
            return render(request, 'myapp/generic_response.html', {'response': msg})
    else:
        form = ClientForm()
    return render(request, 'myapp/register.html', {'form': form})


@login_required
def myorders(request):
    try:
        client = Client.objects.get(pk=request.user.id)
        orders = Order.objects.filter(client=client)
        return render(request, 'myapp/myorders.html', {'orders': orders, 'client': client})
    except Client.DoesNotExist:
        # return render(request, 'myapp/myorders.html')
        return render(request, 'myapp/generic_response.html', {'response': 'You are not a registered client!!'})


@login_required
def myprofile(request):
    try:
        client = Client.objects.get(pk=request.user.id)

        if request.method == 'POST':
            form = ClientForm(request.POST, request.FILES or None, instance=client)
            if form.is_valid() and form.has_changed():
                client = form.save(commit=False)
                if 'password' in form.changed_data:
                    client.set_password(client.password)
                client.save()
                form.save_m2m()

                msg = 'Your Client Profile is Updated'
                return render(request, 'myapp/generic_response.html', {'response': msg})
        else:
            form = ClientForm(instance=client)

templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <p> {{x}} </p>
    <br/>
    <h5>Number of visits: {{ about_visits }}</h5>
{% endblock %}

templates/myapp/about0.html
<p> {{x}} </p̀>
<p><a href="/myapp/lab6a">Index page</a></p>
<p><a href="{% url "myapp:new_index" %}">Index page using url namespacing</a></p>

templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div class="container">
            <header class="d-flex flex-wrap justify-content-center border-bottom">
                    <a href="{% url 'myapp:myprofile' %} " class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                        <span class="fs-4">{% block myhdg %}Hello {{ request.user.first_name }}{% endblock %}</span>
                    </a>
                <ul class="nav nav-pills">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'myapp:myorders' %}" class="nav-link">My Orders</a></li>
                    <li class="nav-item"><a href="{% url 'myapp:logout' %}" class="nav-link">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'myapp:login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{% url 'myapp:register' %}" class="nav-link">Register</a></li>
                    {% endif %}
                </ul>
            </header>
        </div>

        <div class="container">
        {% block body_block %}*** {% endblock %}
        </div>
        <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href = "{% url 'myapp:part2_index' %}" class="nav-link px-2 text-muted">Home</a><br/></li>
            <li class="nav-item"><a href = "{% url 'myapp:products' %}" class="nav-link px-2 text-muted">Products</a><br/></li>
            <li class="nav-item"><a href="{% url 'myapp:part2_about' %}" class="nav-link px-2 text-muted">About</a><br/></li>
            </ul>
            <p class="text-center text-muted">© Alpha Coders</p>
        </footer>
        </div>
    </body>
</html>

templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<h2>Showing all prodcuts from the {{ category.name }} category:</h2>
<p>Location is : {{category.warehouse}}</p>
<table id="prodTable">
<thead>
<tr>
    <th></th>
  <th>Name</th>
  <th>Price</th>
  <th>Stock</th>
  <th>Available</th>
  <th>Description</th>
</tr>
</thead>
<tbody>
{% for product in products %}
<tr>
    <td></td>
    <td> <a href="{% url "myapp:productdetail" product.id %}"> {{ product.name }}</a></td>
    <td> {{ product.price }}</td>
    <td> {{ product.stock }}</td>
    <td> {{ product.available }}</td>
    <td> {{ product.description }}</td>
</tr>
{% endfor %}
</tbody>
</table>

    <script>
        $(document).ready(function () {
           $('#prodTable').DataTable()
        });
    </script>
{% endblock %}

templates/myapp/detail0.html
<html>
<body>

<h1>Showing all prodcuts of the category mentioned by the user in the URL :</h1>
<p>Location is : {{category.warehouse}}</p>
<table>
<tr>
  <th>Name</th>
  <th>Price</th>
  <th>Stock</th>
  <th>Available</th>
  <th>Description</th>
</tr>
{% for product in products %}
<tr>
  <td> {{ product.name }}</td>
  <td> {{ product.price }}</td>
  <td> {{ product.stock }}</td>
  <td> {{ product.available }}</td>
  <td> {{ product.description }}</td>
</tr>
{% endfor %}
</table>
<p><a href="{% url "myapp:new_index" %}">Index page</a></p>
<p><a href="{% url "myapp:new_about" %}">About page</a></p>
</body>
</html>

templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<p>Last Login: {{ last_login }}</p>
{% if cat_list %}
    <h2>Categories</h2>
    <table id="catTable">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Warehouse</th>
            </tr>
        <thead>
        <tbody>
            {% for cat in cat_list %}
            <tr>
                <td></td>
                <td> <a href="{% url "myapp:part2_detail" cat.id %}"> {{ cat.name }}</a></td>
                <td> {{ cat.warehouse }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        $(document).ready(function () {
           $('#catTable').DataTable()
        });
    </script>

{% endif %}
{% endblock %}

templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>

<body>
    {% if cat_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for cat in cat_list %}
                <li> <a href="{% url "myapp:new_detail" cat.id %}">{{ cat.name}}</a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    <p><a href="/myapp/lab6a/about">About page</a></p>
    <p><a href="{% url "myapp:new_about" %}">About page using url namespacing</a></p>
</body>
</html>

templates/myapp/interest_response.html
{% extends 'myapp/base.html' %}
{% block title %}
    Product Available
{% endblock %}
{% block body_block %}
    <h2>Interest Response Status</h2>
    <p>{{ msg }}</p>
    <br/>

{% endblock %}

templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <div>
        <form class="form" method="post">
            {% csrf_token%}

            <div class="container">
                <div class="imgcontainer">
                    <img class="avatar" src="https://www.uwindsor.ca/sites/default/files/uwindsor-new-logo-desktop_1024x768_1.jpg" alt="Avatar" class="avatar">
                </div>
                <div>
                    <label for="exampleInputUserName" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" />
                </div>
                <div>
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" />
                </div>
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                <button type="submit" class="hbar1">Login</button>
            </div>
            <div class="row mb-4">
                <div class="col">
                    <a href="{% url 'myapp:reset_password' %}">Forgot Password</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if client %}
{#        <h3>{{ client.first_name }} {{ client.last_name }}</h3>#}
        {% if client.image %}
        <div class="imgcontainer">
            <img class="avatar" src="{{ client.image.url }}" alt="Avatar" class="avatar">
        </div>
        {% endif %}
        {% if orders %}
            {% if orders|length > 0 %}
                <h3> Your Orders</h3>
                <table id="orders">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr class="width-80">
                            <td></td>
                            <td>{{ order.product.name }}</td>
                            <td>{{ order.product.price }}</td>
                            <td>{{ order.get_order_status_display }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            {% else %}
                <strong>No Order Placed</strong>
        {% endif %}
    {% else %}
        <strong> You are not a registered client!!</strong>
    {% endif %}
    <script>
        $(document).ready(function () {
           $('#orders').DataTable()
        });
    </script>
{% endblock %}

templates/myapp/myprofile.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if client %}
        {% if client.image %}
        <div class="imgcontainer">
            <img class="avatar" src="{{ client.image.url }}" alt="Avatar" class="avatar">
        </div>
        {% else %}
            <div class="imgcontainer">
                <img class="avatar" src="https://www.uwindsor.ca/sites/default/files/uwindsor-new-logo-desktop_1024x768_1.jpg" alt="Avatar" class="avatar">
            </div>
        {% endif %}
        <div>
                <form class="form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="container">
                        {{ form.as_p }}
                        <button type="submit" class="hbar1">Update</button>
                    </div>
                </form>
            <div>
    {% else %}
        <strong> You are not a registered client!!</strong>
    {% endif %}
    <script>
        $(document).ready(function () {
           $('#orders').DataTable()
        });
    </script>
{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block title %}
    Products
{% endblock %}
{% block body_block %}
    <h2>Order Status</h2>
    <p>{{ msg }}</p>
    <br/>

{% endblock %}

templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block title %}
    Product Detail
{% endblock %}
{% block body_block %}
    {% if product.available == True %}
        <h2>{{ product.name }}</h2>
        <p>Interested: {{ product.interested }}</p>
        <p>Price: ${{ product.price }}</p>
    {% else %}
        <h2>Product not Available</h2>
        <p>Sorry! The Product is not available.</p>
    {% endif %}
    <form method="post">
        {% csrf_token%}
        <div class="form-group">
        {{ form}}
        </div>
        <div class="flex">
        <br/>
        <button type="submit">Submit</button>
        </div>
{% endblock %}

templates/myapp/reset_password.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <div>
        <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="container">
                    {% if email %}
                        <span class="lead">Your new password is sent to: {{ email }} </span><br><br>
                        <span class="lead">If you haven't received the email, check your spam folder</span><br><br>
                        <a class="lead" href="{% url "myapp:login" %}"> Login</a>
                    {% else %}
                        <label for="username">Username</label>
                        <input type="text" placeholder="Enter Username" name="username" class="form-control" required>
                        <button type="submit">Submit</button>
                    {% endif %}
                    </div>
            </form>
    </div>
{% endblock %}